version: '3.8'

services:
  # Your API service
  esp32api:
    container_name: ESP32Api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "15000:15000"
    depends_on:
      - esp32mysql

  esp32mysql:
    container_name: ESP32mysql
    image: mysql
    environment:
      - MYSQL_DATABASE=esp32db
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3310:3306"
    volumes:
      - ./database:/docker-entrypoint-initdb.d # Mount initialization scripts